### ISSUE TITLE
Followup 1-pager tasks

### ISSUE THREAD

**Issue by ChristinaLast** [AQ-AI/AQ-AI.github.io#15]
## Tasks
- [x] Update website in October so make sure the website is up!
- [x] Country office reach out (Climate change and India) portfolio
- [x] 3-pager deck (deadline 2022-09-10) drafting requirements [here](https://docs.google.com/presentation/d/1_ncjyFkL8Mm1h8Lb_EK93fWnQ5xbQlpO4fTz54phcd4/edit#slide=id.g15136e3f689_0_5)
- [x] Madison to send you deck to build off (couple hrs)
- [x] Madison intro to Thinking Machines
- [x] Madison to intro Giga

**Comment by ChristinaLast** [comment]
Slide deck [here](https://docs.google.com/presentation/d/14KLwQWlqs-dfUm6LS85aj9neNrCWg5AE/edit?usp=sharing&ouid=113981413364751803856&rtpof=true&sd=true)
