### ISSUE TITLE
Meeting to discuss next 2 week sprint

### ISSUE THREAD

**Issue by ChristinaLast** [AQ-AI/AQ-AI.github.io#18]
- [x] Discuss next 2 weeks plan and milestones
- [x] onboarding lili
- [x] tech legal request email
- [x] pollution prediction for Dehli (vrt deep dive required [here](https://github.com/AQ-AI/AQ-AI.github.io/issues/19))
- [x] UNICEF blog (draft [here](https://unicef.sharepoint.com/:w:/r/teams/OOI/_layouts/15/Doc.aspx?sourcedoc=%7B0741FC57-7CE7-483E-8CF3-44CADD9FD536%7D&file=Draft%20Blog%20Details_Template_AQAI.docx&action=default&mobileredirect=true))
- [x] Identify open licensing strategy [issue 61](https://github.com/AQ-AI/open-geo-engine/issues/61)
- [x] Update website [issue 1](https://github.com/AQ-AI/AQ-AI.github.io/issues/1)
- [x] Project charter and community statement [issue 6](https://github.com/AQ-AI/openaq-engine/issues/6)

### Outputs
- [x] email Madison @ChristinaLast availability for Thinking Machines call
