### ISSUE TITLE
Scaleaway Onboarding

### ISSUE THREAD

**Issue by ChristinaLast** [AQ-AI/AQ-AI.github.io#34]
## Tasks 
- [x] Please create a Organisation ID here (if you don’t already have one) and send it to me (ex: 11a2bbb3-c4dd-555e-F6gg-h7ijklm88910)
- [ ] Book a slot in my agenda to have our initial call in the coming days
- [x] Join our Scaleway Community Slack to be invited to our private channel (Startup Program) where all information related to the program is communicated. We suggest that you introduce yourself to the other members :)
- [x] Read the Onboarding Booklet
- [ ]  Make an appointment with Maxime for your onboarding
- [ ] Register to Scaleway console & share your ID with Maxime
- [ ] Make an appointment with your Account Manager - cc’d in the welcoming email Maxime sent you - who will schedule a call for you with our Solution Architect team
- [ ]  Send an HD .png logo with transparent background to Sarah
- [ ]  Register on our Scaleway Community Slack and introduce yourself to the other members
