### ISSUE TITLE
Complete Ivan deployment-ready repo checklist

### ISSUE THREAD

**Issue by ChristinaLast** [AQ-AI/AQ-AI.github.io#40]
- [x] Semantic Versioning (SemVer) is just one versioning scheme. There are others, e.g., CalVer used by pip
The important fact to realize is that the versioning scheme is a "social contract", not a technical one. There is no way pip/poetry/conda can enforce that your changes follow Semantic Versioning's rules
- [ ] For connecting up to 20 different computers (including EC2, mobile devices) you can use Tailscale 
  - It's the easiest to use VPN service available
  - I'm suggesting this only for development not for production usage. In production you should have a proper IP / DNS configuration
- [ ] For your issue regarding authentication with Google Earth Engine, you must use a Service Account (machine-to-machine) authentication
- [ ] If you want a way to encrypt your secrets but keep them in the same repo, you can look at Mozilla SOPS
- [ ] Here you have an example of a full CI/CD pipeline that uses AWS Elastic Beanstalk for managing service
https://github.com/yvant-coop/OoI-Intern-Assessment
  - In this example we use:
    - Docker and docker-compose for development and production
    - AWS Parameter Store for secrets, See: .ebextensions/init.config
